# Generated by Django 3.2 on 2021-04-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='download.jpeg', null=True, upload_to='profile')),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='rator/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='rater.profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, max_length=300)),
                ('design_rate', models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')])),
                ('usability_rate', models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')])),
                ('content_rate', models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rater.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rater.profile')),
            ],
        ),
    ]
