# Generated by Django 3.2 on 2021-04-08 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rater', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, max_length=300)),
                ('design_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - 1'), (2, '2 - 2'), (3, '3 - 3'), (4, '4 - 4'), (5, '5 - 5'), (6, '6 - 6'), (7, '7 - 7'), (8, '8 - 8'), (9, '9 - 9'), (10, '10 - 10')])),
                ('usability_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - 1'), (2, '2 - 2'), (3, '3 - 3'), (4, '4 - 4'), (5, '5 - 5'), (6, '6 - 6'), (7, '7 - 7'), (8, '8 - 8'), (9, '9 - 9'), (10, '10 - 10')])),
                ('content_rate', models.PositiveSmallIntegerField(choices=[(1, '1 - 1'), (2, '2 - 2'), (3, '3 - 3'), (4, '4 - 4'), (5, '5 - 5'), (6, '6 - 6'), (7, '7 - 7'), (8, '8 - 8'), (9, '9 - 9'), (10, '10 - 10')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rater.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
