# Generated by Django 3.2 on 2021-04-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='design_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='rater.project'),
        ),
        migrations.AlterField(
            model_name='review',
            name='usability_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')]),
        ),
    ]
